## Reference
# https://www.atlantic.net/vps-hosting/how-to-deploy-a-php-application-with-nginx-and-mysql-using-docker-and-docker-compose/

# LAMP STACK
version: '3'
services:
  
  #Nginx Service
  nginx:   
    #image: nginx:1.25.2-alpine
    #image: nginx:latest
    build: ./nginx/
    container_name: nginx-container  
    ports:   
      - 8081:80
    links:
      - php
    #volumes:
    #  - ./www/html/:/var/www/html/
    volumes_from:  
      - app-data

  # php service
  php:
    build: ./php/
    #image: php:7.0-fpm
    container_name: php-container
    expose:
      - 9000
    links:
      - mysql
    #volumes:
    #  - ./www/html/:/var/www/html/
    volumes_from:  
      - app-data

  # php-data service
  app-data:    
    image: php:7.0-fpm  
    container_name: app-data-container  
    volumes:  
      - ./www/html/:/var/www/html/  
    command: "true"

  # mysql service
  mysql:    
    image: mysql:5.7  
    container_name: mysql-container  
    volumes_from:  
      - mysql-data  
    environment:  
      MYSQL_ROOT_PASSWORD: secret  
      MYSQL_DATABASE: mydb  
      MYSQL_USER: myuser  
      MYSQL_PASSWORD: password 
  
  # mysql-data service
  mysql-data:    
    image: mysql:5.7  
    container_name: mysql-data-container  
    volumes:  
      - /var/lib/mysql  
    command: "true" 